### ISSUE TITLE
Failed to Install the package

### ISSUE THREAD

**Issue by idkmew** [SkylarKaf/Elaina-MD#1]
kok sy coba malah ndak bisa di install yak packageny gagal, gaada muncul module" yg harusny ada klo pas npm i

**Comment by SkylarKaf** [comment]
Kamu install nya dmn?

**Comment by idkmew** [comment]
> Kamu install nya dmn?

Win, cmd

**Comment by SkylarKaf** [comment]
Chat di wa aja biar gampang [Wa](http://wa.me//6282331660134)

**Comment by idkmew** [comment]
![image](https://user-images.githubusercontent.com/72456125/217781507-15e2e192-93d9-42e5-8fdc-576261b0076a.png)
gini jadiny, maap gabisa via wa, soalny lagi ke fc wany

**Comment by SkylarKaf** [comment]
Apakah ada dir package-lock.json? Atau jika masib error coba lihat 
[Github npm issue](https://github.com/npm/npm/issues/17444)

**Comment by idkmew** [comment]
> Apakah ada dir package-lock.json? Atau jika masib error coba lihat [Github npm issue](https://github.com/npm/npm/issues/17444)

dah nyoba ngikutin bbrpa saran di https://github.com/npm/npm/issues/17444 dan emng gaada package-lock.jsonny and ttp gabisa rupanya

**Comment by SkylarKaf** [comment]
🤔🤔
